apiVersion: apps/v1
kind: Deployment
metadata:
  # namespace: default
  name: applicationset-controller
  labels:
    app: audit-pod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: audit-pod
  template:
    metadata:
      labels:
        app: audit-pod
    spec :
      hostIPC: true
      hostPID: true
      containers :
        -
          name : applicationset-controller
          env :
            -
              name : ROOT_PASSWORD
              value : "rootpasswd"
          image : hashicorp/http-echo:0.2.3
          securityContext :
            allowPrivilegeEscalation : true
            privileged: true
        -
          name : applicationset-controller-repo
          env :
            -
              name : azure_batch_key
              value : "Hello from the environment"
          image : hashicorp/http-echo:0.2.3
          securityContext :
            allowPrivilegeEscalation : true
