apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      hostIPC: true
      hostPID: true
      containers:
      - name: nginx
        securityContext:
          runAsUser: 0
          runAsNonRoot: false
          allowPrivilegeEscalation: true
          # runAsNonRoot: true
        image: nginx:1.14.2
        ports:
        - containerPort: 80
