apiversion: v1
automountserviceaccounttoken: null
kind: Pod
metadata:
  creationTimestamp: "2026-07-27T04:11:21Z"
  generateName: cowaggregatorservice-hpa-586b964596-
  generation: 1
  labels:
    app: cowaggregatorservice-hpa
    pod-template-hash: 586b964596
  name: cowaggregatorservice-hpa-586b964596-4t7bg
  namespace: dev-cc
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: cowaggregatorservice-hpa-586b964596
    uid: 8f2c420f-fa17-4046-930e-f57010fb09d6
  resourceVersion: 635521433
  uid: 8c7c3e6e-f7d5-485c-9a31-ac8b570635e3
name: dev-cc/cowaggregatorservice-hpa-586b964596-4t7bg
spec:
  automountServiceAccountToken: false
  containers:
  - envFrom:
    - configMapRef:
        name: cow-env
    image: continube.azurecr.io/compliancecow/dev/cowaggregatorservice:hpa
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 10
      httpGet:
        path: /healthcheck
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 100
      periodSeconds: 60
      successThreshold: 1
      timeoutSeconds: 10
    name: cowaggregatorservice-hpa
    readinessProbe:
      failureThreshold: 2
      httpGet:
        path: /healthcheck
        port: 8080
        scheme: HTTP
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 10
    resources:
      limits:
        cpu: 300m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 250Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-c8knm
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: aks-nodepool1-29681506-vmss00001g
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    runAsNonRoot: true
    runAsUser: 10000
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: kube-api-access-c8knm
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-07-27T04:11:23Z"
    observedGeneration: 1
    status: true
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-07-27T04:11:21Z"
    observedGeneration: 1
    status: true
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-07-27T04:11:23Z"
    observedGeneration: 1
    status: true
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-07-27T04:11:23Z"
    observedGeneration: 1
    status: true
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-07-27T04:11:21Z"
    observedGeneration: 1
    status: true
    type: PodScheduled
  containerStatuses:
  - allocatedResources:
      cpu: 100m
      memory: 250Mi
    containerID: containerd://6ff8991637e9a50fb81e646b3bf2af3dbce9c0785ab20399043b5d61d91a4137
    image: continube.azurecr.io/compliancecow/dev/cowaggregatorservice:hpa
    imageID: continube.azurecr.io/compliancecow/dev/cowaggregatorservice@sha256:40c862ae1f1db26744e703cf52b8fdf82885093ecbdbf78c933526f21d7c55b8
    lastState: null
    name: cowaggregatorservice-hpa
    ready: true
    resources:
      limits:
        cpu: 300m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 250Mi
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-07-27T04:11:22Z"
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-c8knm
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 10.4.16.145
  hostIPs:
  - ip: 10.4.16.145
  observedGeneration: 1
  phase: Running
  podIP: 10.4.16.168
  podIPs:
  - ip: 10.4.16.168
  qosClass: Burstable
  startTime: "2026-07-27T04:11:21Z"
