apiversion: v1
automountserviceaccounttoken: null
kind: Pod
metadata:
  creationTimestamp: "2026-07-28T08:57:57Z"
  generateName: cowactionservice-9845f6f8-
  generation: 1
  labels:
    app: cowactionservice
    pod-template-hash: 9845f6f8
  name: cowactionservice-9845f6f8-5klr5
  namespace: dev-cc
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: cowactionservice-9845f6f8
    uid: 761ebd04-7011-4817-ae3f-ef3490588ea0
  resourceVersion: 636122720
  uid: 751010c0-ec22-464d-a691-45390aec1267
name: dev-cc/cowactionservice-9845f6f8-5klr5
spec:
  automountServiceAccountToken: false
  containers:
  - envFrom:
    - configMapRef:
        name: cow-env
    image: continube.azurecr.io/compliancecow/dev/cowactionservice:R258.2160-A
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthcheck
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 100
      successThreshold: 1
      timeoutSeconds: 10
    name: cowactionservice
    ports:
    - containerPort: 8080
      protocol: TCP
    resources:
      limits:
        cpu: 300m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 250Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-d2bfl
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: aks-nodepool1-29681506-vmss00001g
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    runAsNonRoot: true
    runAsUser: 10000
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: kube-api-access-d2bfl
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-07-28T08:58:00Z"
    observedGeneration: 1
    status: true
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-07-28T08:57:57Z"
    observedGeneration: 1
    status: true
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-07-28T08:58:00Z"
    observedGeneration: 1
    status: true
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-07-28T08:58:00Z"
    observedGeneration: 1
    status: true
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-07-28T08:57:57Z"
    observedGeneration: 1
    status: true
    type: PodScheduled
  containerStatuses:
  - allocatedResources:
      cpu: 100m
      memory: 250Mi
    containerID: containerd://2e885dd4f507bb08ad18f8afe9d4c16c3e18ed5c30638b2ca70ad9949323d027
    image: continube.azurecr.io/compliancecow/dev/cowactionservice:R258.2160-A
    imageID: continube.azurecr.io/compliancecow/dev/cowactionservice@sha256:65dd94020fdfd7e8ca7693a5bac9946bd54649f74e16ecb1aa219af5d5713eeb
    lastState: null
    name: cowactionservice
    ready: true
    resources:
      limits:
        cpu: 300m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 250Mi
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-07-28T08:57:59Z"
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-d2bfl
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 10.4.16.145
  hostIPs:
  - ip: 10.4.16.145
  observedGeneration: 1
  phase: Running
  podIP: 10.4.16.178
  podIPs:
  - ip: 10.4.16.178
  qosClass: Burstable
  startTime: "2026-07-28T08:57:57Z"
