apiversion: v1
automountserviceaccounttoken: null
kind: Pod
metadata:
  creationTimestamp: "2026-07-28T08:58:03Z"
  generateName: cowcustomeronboardingservice-7b446455b9-
  generation: 1
  labels:
    app: cowcustomeronboardingservice
    pod-template-hash: 7b446455b9
  name: cowcustomeronboardingservice-7b446455b9-7pnbm
  namespace: dev-cc
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: cowcustomeronboardingservice-7b446455b9
    uid: dcb41bff-f1ad-400c-a1b1-00586fe4aad4
  resourceVersion: 636123867
  uid: 0c83ccc2-b0ea-43b9-94d2-fa98d8d8b39c
name: dev-cc/cowcustomeronboardingservice-7b446455b9-7pnbm
spec:
  automountServiceAccountToken: false
  containers:
  - envFrom:
    - configMapRef:
        name: cow-env
    image: continube.azurecr.io/compliancecow/dev/cowcustomeronboardingservice:R258.2160-A
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthcheck
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 100
      successThreshold: 1
      timeoutSeconds: 10
    name: cowcustomeronboardingservice
    ports:
    - containerPort: 8080
      protocol: TCP
    resources:
      limits:
        cpu: 300m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 250Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-dvqj7
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: aks-nodepool1-29681506-vmss000019
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    runAsNonRoot: true
    runAsUser: 10000
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: kube-api-access-dvqj7
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-07-28T08:58:14Z"
    observedGeneration: 1
    status: true
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-07-28T08:58:11Z"
    observedGeneration: 1
    status: true
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-07-28T08:58:14Z"
    observedGeneration: 1
    status: true
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-07-28T08:58:14Z"
    observedGeneration: 1
    status: true
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-07-28T08:58:11Z"
    observedGeneration: 1
    status: true
    type: PodScheduled
  containerStatuses:
  - allocatedResources:
      cpu: 100m
      memory: 250Mi
    containerID: containerd://259600cd2405137791a2c011380ea07d582b28df8e727107b68f39b75923ab34
    image: continube.azurecr.io/compliancecow/dev/cowcustomeronboardingservice:R258.2160-A
    imageID: continube.azurecr.io/compliancecow/dev/cowcustomeronboardingservice@sha256:f3546dc5392a1f574eacbf7b757df530209b8bc5b34e07ccbde847f0099c564d
    lastState: null
    name: cowcustomeronboardingservice
    ready: true
    resources:
      limits:
        cpu: 300m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 250Mi
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-07-28T08:58:13Z"
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-dvqj7
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 10.4.16.193
  hostIPs:
  - ip: 10.4.16.193
  observedGeneration: 1
  phase: Running
  podIP: 10.4.16.22
  podIPs:
  - ip: 10.4.16.22
  qosClass: Burstable
  startTime: "2026-07-28T08:58:11Z"
