{
 "title": "ArtifactHub",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Successful requests processed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_count{path!=\"/\",status=~\"OK|Created|No Content\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Successful requests",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_count{path!=\"/\",status!=\"Internal Server Error\"}[$__interval])) / sum(rate(http_request_duration_count{path!=\"/\"}[$__interval])) * 100"
    }
   ]
  },
  {
   "title": "Failed requests processed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_count{path!=\"/\",status=\"Internal Server Error\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Last day requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_count{path!=\"/\"}[$__rate_interval]))",
     "legendFormat": "Hour requests"
    }
   ]
  },
  {
   "title": "Helm CLI searches",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_count{path=\"/api/chartsvc/v1/charts/search\"}[$__rate_interval]))",
     "legendFormat": "Searches in 15m window"
    }
   ]
  },
  {
   "title": "Last month requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_count{path!=\"/\"}[$__rate_interval]))",
     "legendFormat": "Daily requests"
    }
   ]
  },
  { "title": "API latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "API average latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_sum{path=~\"/api/.*\",status=~\"OK|Created|No Content\"}[$__rate_interval])) / sum(rate(http_request_duration_count{path=~\"/api/.*\",status=~\"OK|Created|No Content\"}[$__rate_interval]))",
     "legendFormat": "API average latency"
    }
   ]
  },
  { "title": "Requests rate (per second)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Successful requests rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_count{path=~\"/api/.*\",status=~\"OK|Created|No Content\"}[$__rate_interval])) by (path)",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Failed requests rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_count{path=~\"/api/.*\",status=\"Internal Server Error\"}[$__rate_interval])) by (path)",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  { "title": "Requests duration (in seconds)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Successful requests duration (p95)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_bucket{path=~\"/api/.*\",status=~\"OK|Created|No Content\"}[$__rate_interval])) by (path, le))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Failed requests duration (p95)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_bucket{path=~\"/api/.*\",status=\"Internal Server Error\"}[$__rate_interval])) by (path, le))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Successful requests duration (p75)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_request_duration_bucket{path=~\"/api/.*\",status=~\"OK|Created|No Content\"}[$__rate_interval])) by (path, le))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Failed requests duration (p75)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 45 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_request_duration_bucket{path=~\"/api/.*\",status=\"Internal Server Error\"}[$__rate_interval])) by (path, le))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Successful requests duration (p50)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_bucket{path=~\"/api/.*\",status=~\"OK|Created|No Content\"}[$__rate_interval])) by (path, le))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Failed requests duration (p50)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 55 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_bucket{path=~\"/api/.*\",status=\"Internal Server Error\"}[$__rate_interval])) by (path, le))",
     "legendFormat": "{{ path }}"
    }
   ]
  }
 ]
}